services:
  nginx:
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
  blocktool:
    image: 128992268287.dkr.ecr.us-east-1.amazonaws.com/blocktool:3
