version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
  blocktool:
    ports:
      - 4000:4000
    environment:
      - DB_PATH=/usr/app/db/db.sqlite
    volumes:
      - ./db:/usr/app/db:rw
