version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - $NGINX_CONF_PATH:/etc/nginx/conf.d/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
  blocktool:
    image: 128992268287.dkr.ecr.us-east-1.amazonaws.com/blocktool:1
    ports:
      - 4000:4000
    environment:
      - DB_PATH=/usr/app/db/db.sqlite
    volumes:
      - ./db:/usr/app/db:rw
